sudo: required
services:
  - docker

before_install:
  - docker build -t erickmauricio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true erickmauricio/react-test npm test

after_success:
  - docker build -t erickmauricio/multi-client ./client
  - docker build -t erickmauricio/multi-nginx ./nginx
  - docker build -t erickmauricio/multi-server ./server
  - docker build -t erickmauricio/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # push built images to docker hub
  - docker push erickmauricio/multi-client
  - docker push erickmauricio/multi-nginx
  - docker push erickmauricio/multi-server
  - docker push erickmauricio/multi-worker