sudo: required
services:
  - docker

before_install:
  - docker build -t erickmauricio/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true erickmauricio/react-test npm test

after_success:
  - docker build -t erickmauricio/multi-client ./client
  - docker build -t erickmauricio/multi-nginx ./nginx
  - docker build -t erickmauricio/multi-server ./server
  - docker build -t erickmauricio/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push built images to docker hub
  - docker push erickmauricio/multi-client
  - docker push erickmauricio/multi-nginx
  - docker push erickmauricio/multi-server
  - docker push erickmauricio/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-834731668027"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY